# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
version: 2.1

jobs:
  Build:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: Install the dependencies
          command: npm install
      - run:
          name: Build the Control Panel
          command: npm run build
      - run:
          name: Build the Addon
          command: npm run build-addon

  Addon unit tests:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: Install the dependencies
          command: npm install
      - run:
          name: MochaJS unit tests
          command: npm run test-addon

  Addon code linting:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: Install the dependencies
          command: npm install
      - run:
          name: Build the Control Panel
          command: npm run build
      - run:
          name: Build the Addon
          command: npm run build-addon
      - run:
          name: Run linting
          command: npm run lint

  Firefox integration tests:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: Install the dependencies
          command: npm install && sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa && sudo apt update && sudo apt install firefox-trunk
      - run:
          name: Download and unpack GeckoDriver for Selenium
          command: wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz && tar zxf geckodriver-v0.28.0-linux64.tar.gz
      - run:
          name: Run Selenium tests
          command: export PATH=.:$PATH && npm run test-integration

workflows:
  version: 2
  ci:
    jobs:
      - Build
      - Addon unit tests
      - Addon code linting
      - Firefox integration tests
